# Generated by Django 3.2.20 on 2023-09-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bhfh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dfd34',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gfhfj', models.BigIntegerField()),
            ],
        ),
    ]
